create database examdb;
use examdb;
show tables;
create table student(s_id int, name char(35), age int);
show tables;
desc student;
insert into student values (1,'tom',32);
select *from student;
insert into student values (2,'anup',22);
select *from student;
insert into student values (3,'harish',50);
select *from student;
insert into student values (4,'bhupal',69);
select *from student;
insert into student values (5,'sujith',24);
select *from student;
desc student;
select *from student;
create table timetab (doj datetime, toj timestamp);
desc timetab;
insert into timetab values ('1977-01-22 11:11:11','1982-02-02 10:30:00');
select *from timetab;
insert into timetab values ('1977-01-22 11:11:11',now());
select *from timetab;
desc student;
alter table student add column (subject varchar(20));
desc student;
select *from student;
alter table student  modify column subject char(20);
desc student;
alter table student drop column subject;
desc student;
select *from student limit 5;
alter table student add column subject1 char(20) default 'physics';
desc student;
select*from student;
alter table student  drop column subject;
select * from student;
drop table timetab;
show tables;
alter table students rename to mystudent;
show tables;
rename table mystudent to student;
show tables;
select * from student;
select * from student;
insert into student values (6,'deva',35,'chemistry');
select * from student;
insert into student  (s_id,name,age) values (7,'teja',45);
select * from student;
insert into student values (8,'shalom',42,'maths'),(8,'sai',53,'DME2');
select* from student;
select*from student limit 3;
update student set age  = 20 where name='harish';
delete from student where s_id=7;
truncate table student;
select * from student;
show tables;
drop table student;
show tables;
create table students (sid int, name varchar(20), age int,subject varchar(20));
show tables ;
insert into students values (1,'anup',22,'data science'),(2,'harish',23,'data science'),(3,'bhupal',24,'data science');
select*from students;
select sid,name,subject from students;
select*from students where sid=1 and subject = 'data science';
select*from students where sid=1 or subject = 'data science';
select * from students;
select * from students where sid =1 or sid=3;
select * from students where sid in (2,3);




